import type { DesignStyle } from '../types';

export const DESIGN_STYLES: DesignStyle[] = [
  { id: 'modern', name: 'Modern', nameRu: 'Современный', emoji: '✨' },
  { id: 'scandinavian', name: 'Scandinavian', nameRu: 'Скандинавский', emoji: '🌲' },
  { id: 'bohemian', name: 'Bohemian', nameRu: 'Бохо', emoji: '🎨' },
  { id: 'minimalist', name: 'Minimalist', nameRu: 'Минимализм', emoji: '◻️' },
  { id: 'industrial', name: 'Industrial', nameRu: 'Лофт', emoji: '🏭' },
  { id: 'mid-century', name: 'Mid-Century', nameRu: 'Mid-Century', emoji: '🕰️' },
  { id: 'japanese', name: 'Japanese', nameRu: 'Японский', emoji: '🏯' },
  { id: 'art-deco', name: 'Art Deco', nameRu: 'Ар-Деко', emoji: '💎' },
  { id: 'farmhouse', name: 'Farmhouse', nameRu: 'Кантри', emoji: '🌾' },
  { id: 'coastal', name: 'Coastal', nameRu: 'Прибрежный', emoji: '🐚' },
  { id: 'contemporary', name: 'Contemporary', nameRu: 'Современный', emoji: '🆕' },
  { id: 'traditional', name: 'Traditional', nameRu: 'Классический', emoji: '👑' },
  { id: 'rustic', name: 'Rustic', nameRu: 'Рустик', emoji: '🪵' },
  { id: 'tropical', name: 'Tropical', nameRu: 'Тропический', emoji: '🌴' },
  { id: 'neoclassical', name: 'Neoclassical', nameRu: 'Неоклассика', emoji: '🏛️' },
  { id: 'loft', name: 'Loft', nameRu: 'Лофт', emoji: '🧱' },
  { id: 'eclectic', name: 'Eclectic', nameRu: 'Эклектика', emoji: '🎭' },
  { id: 'mediterranean', name: 'Mediterranean', nameRu: 'Средиземноморский', emoji: '🌊' },
  { id: 'vintage', name: 'Vintage', nameRu: 'Винтаж', emoji: '📻' },
  { id: 'gothic', name: 'Gothic', nameRu: 'Готика', emoji: '🦇' },
  { id: 'provence', name: 'Provence', nameRu: 'Прованс', emoji: '🌸' },
  { id: 'moroccan', name: 'Moroccan', nameRu: 'Марокканский', emoji: '🕌' },
  { id: 'victorian', name: 'Victorian', nameRu: 'Викторианский', emoji: '🕯️' },
  { id: 'baroque', name: 'Baroque', nameRu: 'Барокко', emoji: '🏰' },
  { id: 'cyberpunk', name: 'Cyberpunk', nameRu: 'Киберпанк', emoji: '⚡' },
  { id: 'zen', name: 'Zen', nameRu: 'Дзен', emoji: '☯️' },
  { id: 'wabi-sabi', name: 'Wabi-Sabi', nameRu: 'Ваби-Саби', emoji: '🍂' },
  { id: 'hollywood-regency', name: 'Hollywood Regency', nameRu: 'Голливудский', emoji: '🎬' },
  { id: 'shabby-chic', name: 'Shabby Chic', nameRu: 'Шебби-Шик', emoji: '🕊️' },
  { id: 'transitional', name: 'Transitional', nameRu: 'Переходный', emoji: '🔄' },
  { id: 'organic-modern', name: 'Organic Modern', nameRu: 'Органический', emoji: '🌿' },
  { id: 'desert-modern', name: 'Desert Modern', nameRu: 'Пустынный', emoji: '🏜️' },
  { id: 'grandmillennial', name: 'Grandmillennial', nameRu: 'Грандмиллениал', emoji: '🌹' },
  { id: 'cottagecore', name: 'Cottagecore', nameRu: 'Коттеджный', emoji: '🏠' },
  { id: 'dark-academia', name: 'Dark Academia', nameRu: 'Тёмная Академия', emoji: '📚' },
  { id: 'light-academia', name: 'Light Academia', nameRu: 'Светлая Академия', emoji: '📖' },
  { id: 'steampunk', name: 'Steampunk', nameRu: 'Стимпанк', emoji: '⚙️' },
];
